CREATE DATABASE IF NOT EXISTS miniwebserver
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE miniwebserver;

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    author VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
